### ISSUE TITLE
EntityFilter

### ISSUE THREAD

**Issue by SinoX1337** [Smesh292/trikz#2]
Hello,

i have one problem can you help me pls?

L 04/19/2022 - 17:38:14: [SM] Unable to load plugin "entityfilter.smx": Native "GetOutputActionCount" was not found

**Comment by Smesh292** [comment]
Download extension from SlidyBat [Here.](https://github.com/SlidyBat/sm-ext-outputinfo) Rename outputinfo.ext.2.sdk2013 to outputinfo.ext
