### ISSUE TITLE
trueexpert_entityfilter.sp Native "GetOutputActionTimesToFire" was not found

### ISSUE THREAD

**Issue by Chocominttt** [Smesh292/trikz#3]
Used your outputinfo.ext.so....Can you give me a copy of addons? ):

**Comment by Smesh292** [comment]
Can you show please sm exts list and sm plugins list ?

**Comment by Smesh292** [comment]
[plugins.zip](https://github.com/Smesh292/trikz/files/10202544/plugins.zip)
